# Generated by Django 5.1.2 on 2024-11-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GestionAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('nombre_accion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('precio_total', models.FloatField()),
                ('porcentaje_ganancia', models.FloatField()),
                ('total_ganancia', models.FloatField()),
            ],
        ),
    ]
