# Generated by Django 5.1.2 on 2024-11-05 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionacciones',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='gestionacciones',
            name='fecha_compra',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gestionacciones',
            name='precio_unitario',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
